//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.34209
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectclient.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WhoisLogon", ReplyAction="http://tempuri.org/IService1/WhoisLogonResponse")]
        string[] WhoisLogon(string tf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MyPosition", ReplyAction="http://tempuri.org/IService1/MyPositionResponse")]
        string[] MyPosition(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TimeToXml", ReplyAction="http://tempuri.org/IService1/TimeToXmlResponse")]
        string[] TimeToXml(System.DateTime start, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MissingLogon", ReplyAction="http://tempuri.org/IService1/MissingLogonResponse")]
        string[] MissingLogon(string info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Missingmember", ReplyAction="http://tempuri.org/IService1/MissingmemberResponse")]
        void Missingmember(string[] name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoadDayTo", ReplyAction="http://tempuri.org/IService1/LoadDayToResponse")]
        string[] LoadDayTo(System.DateTime st, System.DateTime la);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/admininsert", ReplyAction="http://tempuri.org/IService1/admininsertResponse")]
        void admininsert(string name, string id, string password, string phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/adminselect", ReplyAction="http://tempuri.org/IService1/adminselectResponse")]
        string[] adminselect(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/adminupdate", ReplyAction="http://tempuri.org/IService1/adminupdateResponse")]
        void adminupdate(string id, string name, string password, string phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/admindelete", ReplyAction="http://tempuri.org/IService1/admindeleteResponse")]
        void admindelete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/adminidcheck", ReplyAction="http://tempuri.org/IService1/adminidcheckResponse")]
        bool adminidcheck(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insertmember", ReplyAction="http://tempuri.org/IService1/InsertmemberResponse")]
        bool Insertmember(string id, string pwd, string name, string age, string phone, string loginfo, string sex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/relationmember", ReplyAction="http://tempuri.org/IService1/relationmemberResponse")]
        string[] relationmember(string tf);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : projectclient.ServiceReference2.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<projectclient.ServiceReference2.IService1>, projectclient.ServiceReference2.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] WhoisLogon(string tf) {
            return base.Channel.WhoisLogon(tf);
        }
        
        public string[] MyPosition(string id) {
            return base.Channel.MyPosition(id);
        }
        
        public string[] TimeToXml(System.DateTime start, System.DateTime end) {
            return base.Channel.TimeToXml(start, end);
        }
        
        public string[] MissingLogon(string info) {
            return base.Channel.MissingLogon(info);
        }
        
        public void Missingmember(string[] name) {
            base.Channel.Missingmember(name);
        }
        
        public string[] LoadDayTo(System.DateTime st, System.DateTime la) {
            return base.Channel.LoadDayTo(st, la);
        }
        
        public void admininsert(string name, string id, string password, string phone) {
            base.Channel.admininsert(name, id, password, phone);
        }
        
        public string[] adminselect(string id) {
            return base.Channel.adminselect(id);
        }
        
        public void adminupdate(string id, string name, string password, string phone) {
            base.Channel.adminupdate(id, name, password, phone);
        }
        
        public void admindelete(string id) {
            base.Channel.admindelete(id);
        }
        
        public bool adminidcheck(string id) {
            return base.Channel.adminidcheck(id);
        }
        
        public bool Insertmember(string id, string pwd, string name, string age, string phone, string loginfo, string sex) {
            return base.Channel.Insertmember(id, pwd, name, age, phone, loginfo, sex);
        }
        
        public string[] relationmember(string tf) {
            return base.Channel.relationmember(tf);
        }
    }
}
